services:
  webtaller:
    build: 
      context: ..
      dockerfile: ./deploy/Dockerfile
      args:
        - PROYECTO=${PROYECTO}
        - USUARIO=${USUARIO}
        - TIPO=${TIPO}
    container_name: web_taller

    image: dangekid/webtaller:latest
    hostname: web_taller
    env_file:
      - ./.env
      