version: '3.8'

services:
  web:
    build:
      context: /home/dangelo/Documentos/HLC/Docker/Caronte
      dockerfile: Docker/Dockerfiles/sgbd/Dockerfile
      #args: 
      #- USUARIO=oliver
    container_name: ctpbase
    environment:
      - USUARIO=dangelo